{{- if .Values.additionalSecrets.enabled }}
{{- range $secretKey, $secret := .Values.additionalSecrets.secrets }}
{{- if $secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    component: additional-secrets
type: {{ $secret.type }}
data:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}